Mus_PalletTown		equ	0
Mus_Pokecenter		equ	1
Mus_Gym			equ	2
Mus_Cities1		equ	3
Mus_Cities2		equ	4
Mus_Celadon		equ	5
Mus_Cinnabar		equ	6
Mus_Vermillion		equ	7
Mus_Lavender		equ	8
Mus_SSAnne		equ	9
Mus_MeetProfOak		equ	10
Mus_MeetRival		equ	11
Mus_FollowMe		equ	12
Mus_Evolution		equ	13
Mus_PkmnHealed		equ	14
Mus_Routes1		equ	15
Mus_Routes2		equ	16
Mus_Routes3		equ	17
Mus_Routes4		equ	18
Mus_IndigoPlateau	equ	19
Mus_GymLeaderBattle	equ	20
Mus_TrainerBattle	equ	21
Mus_WildBattle		equ	22
Mus_SpecialBattle	equ	23
Mus_FinalBattle		equ	24
Mus_LanceBattle		equ	25
Mus_HaidenBattle	equ	26
Mus_DefeatedTrainer	equ	27
Mus_DefeatedWildMon	equ	28
Mus_DefeatedGymLeader	equ	29
Mus_Title		equ	30
Mus_Credits		equ	31
Mus_HallOfFame		equ	32
Mus_OaksLab		equ	33
Mus_JigglypuffSong	equ	34
Mus_BikeRiding		equ	35
Mus_Surfing		equ	36
Mus_GameCorner		equ	37
Mus_IntroBattle		equ	38
Mus_Dungeon1		equ	39
Mus_Dungeon2		equ	40
Mus_Dungeon3		equ	41
Mus_CinnabarMansion	equ	42
Mus_PokemonTower	equ	43
Mus_SilphCo		equ	44
Mus_MeetEvilTrainer	equ	45
Mus_MeetFemaleTrainer	equ	46
Mus_MeetMaleTrainer	equ	47
Mus_Unused		equ	48
Mus_StevenBattle	equ	49
Mus_Pokeflute		equ	50
Mus_WCS			equ	51
Mus_Pinch		equ	52
Mus_ToyWarrior		equ	53
Mus_MaskedBattle	equ	54
Mus_Touhou3Select	equ	55
Mus_OceanLoader3	equ	56
Mus_ClubLeaderBattle	equ	57